<template>
  <div>
    <a
      id="skip-to-content"
      href="#content">Skip to the content.</a>

    <header
      class="page-header"
      role="banner">
      <h1 class="project-name">vue2-perfect-scrollbar</h1>
      <h2 class="project-tagline">
        Vue.js minimalistic but powerful wrapper for perfect scrollbar
      </h2>
      <a
        href="https://github.com/mercs600/vue2-perfect-scrollbar/tree/master"
        class="btn">
        View on GitHub
      </a>
    </header>

    <main
      id="content"
      class="main-content container"
      role="main">
      <nuxt/>
      <footer class="site-footer">
        <span class="site-footer-owner">
          <a href="https://github.com/mercs600/vue2-perfect-scrollbar/tree/master">vue2-perfect-scrollbar</a> is maintained by @mercs600
        </span>
        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
      </footer>
    </main>
  </div>
</template>

<style lang="scss">
@import "~/styles/jekyll-theme-cayman.scss";
</style>
